import Navbar from "./components/Navbar";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Hydrate from "./components/Hydrate";
import { Sora } from "next/font/google";

const sora = Sora({ weight: ["400", "700"], subsets: ["latin-ext"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // fetch the user
  const session = await getServerSession(authOptions);
  // console.log("session", session);
  return (
    <html lang="en">
      <body className={`md:mx-64 ${sora.className}`}>
        <Hydrate>
          <Navbar expires={session?.expires as string} user={session?.user} />
          {children}
        </Hydrate>
      </body>
    </html>
  );
}
